"""create resource metric snapshots table

Revision ID: 244d89173a65
Revises: 81a2dc4ee707
Create Date: 2026-07-31 00:51:15.209935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244d89173a65'
down_revision: Union[str, Sequence[str], None] = '81a2dc4ee707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_db_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_timestamp', sa.DateTime(), nullable=False),
    sa.Column('average_value', sa.Float(), nullable=False),
    sa.Column('maximum_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_db_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_db_id', 'metric_name', 'metric_timestamp', name='uq_resource_metric_timestamp')
    )
    op.create_index(op.f('ix_resource_metric_snapshots_id'), 'resource_metric_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_resource_metric_snapshots_metric_name'), 'resource_metric_snapshots', ['metric_name'], unique=False)
    op.create_index(op.f('ix_resource_metric_snapshots_metric_timestamp'), 'resource_metric_snapshots', ['metric_timestamp'], unique=False)
    op.create_index(op.f('ix_resource_metric_snapshots_resource_db_id'), 'resource_metric_snapshots', ['resource_db_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_metric_snapshots_resource_db_id'), table_name='resource_metric_snapshots')
    op.drop_index(op.f('ix_resource_metric_snapshots_metric_timestamp'), table_name='resource_metric_snapshots')
    op.drop_index(op.f('ix_resource_metric_snapshots_metric_name'), table_name='resource_metric_snapshots')
    op.drop_index(op.f('ix_resource_metric_snapshots_id'), table_name='resource_metric_snapshots')
    op.drop_table('resource_metric_snapshots')
    # ### end Alembic commands ###
