"""create cloud resources table

Revision ID: 3788c52dc739
Revises: 11152d418792
Create Date: 2026-07-28 01:17:49.497019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3788c52dc739'
down_revision: Union[str, Sequence[str], None] = '11152d418792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aws_account_id', sa.String(length=12), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('availability_zone', sa.String(length=32), nullable=True),
    sa.Column('instance_type', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('launch_time', sa.DateTime(), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('missing_tags', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_account_id', 'region', 'resource_type', 'resource_id', name='uq_cloud_resource_identity')
    )
    op.create_index(op.f('ix_cloud_resources_owner_email'), 'cloud_resources', ['owner_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_resources_owner_email'), table_name='cloud_resources')
    op.drop_table('cloud_resources')
    # ### end Alembic commands ###
