"""create optimization recommendations table

Revision ID: 3cd62af181bf
Revises: a9c021a24306
Create Date: 2026-08-02 15:37:52.049269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd62af181bf'
down_revision: Union[str, Sequence[str], None] = 'a9c021a24306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_cost_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aws_account_id', sa.String(length=20), nullable=False),
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.Column('service_breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_account_id', 'cost_date', name='uq_account_cost_date')
    )
    op.create_index(op.f('ix_daily_cost_snapshots_aws_account_id'), 'daily_cost_snapshots', ['aws_account_id'], unique=False)
    op.create_index(op.f('ix_daily_cost_snapshots_cost_date'), 'daily_cost_snapshots', ['cost_date'], unique=False)
    op.create_index(op.f('ix_daily_cost_snapshots_id'), 'daily_cost_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_cost_snapshots_id'), table_name='daily_cost_snapshots')
    op.drop_index(op.f('ix_daily_cost_snapshots_cost_date'), table_name='daily_cost_snapshots')
    op.drop_index(op.f('ix_daily_cost_snapshots_aws_account_id'), table_name='daily_cost_snapshots')
    op.drop_table('daily_cost_snapshots')
    # ### end Alembic commands ###
