"""create metric anomalies table

Revision ID: a9c021a24306
Revises: 244d89173a65
Create Date: 2026-07-31 01:38:21.030071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c021a24306'
down_revision: Union[str, Sequence[str], None] = '244d89173a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_db_id', sa.Integer(), nullable=False),
    sa.Column('metric_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_snapshot_id'], ['resource_metric_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_db_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_snapshot_id', 'model_name', name='uq_snapshot_model')
    )
    op.create_index(op.f('ix_metric_anomalies_id'), 'metric_anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_metric_anomalies_is_active'), 'metric_anomalies', ['is_active'], unique=False)
    op.create_index(op.f('ix_metric_anomalies_metric_snapshot_id'), 'metric_anomalies', ['metric_snapshot_id'], unique=False)
    op.create_index(op.f('ix_metric_anomalies_resource_db_id'), 'metric_anomalies', ['resource_db_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_anomalies_resource_db_id'), table_name='metric_anomalies')
    op.drop_index(op.f('ix_metric_anomalies_metric_snapshot_id'), table_name='metric_anomalies')
    op.drop_index(op.f('ix_metric_anomalies_is_active'), table_name='metric_anomalies')
    op.drop_index(op.f('ix_metric_anomalies_id'), table_name='metric_anomalies')
    op.drop_table('metric_anomalies')
    # ### end Alembic commands ###
