"""create optimization recommendations table

Revision ID: be3349e8206f
Revises: 3cd62af181bf
Create Date: 2026-08-02 16:00:53.183691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3349e8206f'
down_revision: Union[str, Sequence[str], None] = '3cd62af181bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_db_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('average_cpu', sa.Float(), nullable=True),
    sa.Column('maximum_cpu', sa.Float(), nullable=True),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_db_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_db_id', 'recommendation_type', name='uq_resource_recommendation_type')
    )
    op.create_index(op.f('ix_optimization_recommendations_id'), 'optimization_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_resource_db_id'), 'optimization_recommendations', ['resource_db_id'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_status'), 'optimization_recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_recommendations_status'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_resource_db_id'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_id'), table_name='optimization_recommendations')
    op.drop_table('optimization_recommendations')
    # ### end Alembic commands ###
